name: macOS Interactive Web Terminal

on:
  workflow_dispatch:

jobs:
  interactive-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Launch Interactive Web Terminal (tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          detached: false
